/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.5 Mon Jul 22 14:48:13 2024.
 */

#include <string.h>

#include "Indicators_CANSignal.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

int indicators_indicator_status_pack(
    uint8_t *dst_p,
    const struct indicators_indicator_status_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u8(src_p->right_indicator, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->left_indicator, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->parking_indicator, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->high_beam_indicator, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->low_beam_indicator, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->engine_oil_temperature_indicator, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->seat_belt_indicator, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->engine_malfunction_indicator, 7u, 0x80u);
    dst_p[1] |= pack_left_shift_u8(src_p->doors_open_indicator, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->abs_warning_indicator, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->faulty_right_indicator, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->faulty_left_indicator, 3u, 0x08u);
    dst_p[1] |= pack_left_shift_u8(src_p->engine_oil_indicator, 4u, 0x10u);

    return (5);
}

int indicators_indicator_status_unpack(
    struct indicators_indicator_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->right_indicator = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->left_indicator = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->parking_indicator = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->high_beam_indicator = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->low_beam_indicator = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->engine_oil_temperature_indicator = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->seat_belt_indicator = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->engine_malfunction_indicator = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->doors_open_indicator = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->abs_warning_indicator = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->faulty_right_indicator = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->faulty_left_indicator = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
    dst_p->engine_oil_indicator = unpack_right_shift_u8(src_p[1], 4u, 0x10u);

    return (0);
}

int indicators_indicator_status_init(struct indicators_indicator_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct indicators_indicator_status_t));

    return 0;
}

uint8_t indicators_indicator_status_right_indicator_encode(double value)
{
    return (uint8_t)(value);
}

double indicators_indicator_status_right_indicator_decode(uint8_t value)
{
    return ((double)value);
}

bool indicators_indicator_status_right_indicator_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t indicators_indicator_status_left_indicator_encode(double value)
{
    return (uint8_t)(value);
}

double indicators_indicator_status_left_indicator_decode(uint8_t value)
{
    return ((double)value);
}

bool indicators_indicator_status_left_indicator_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t indicators_indicator_status_parking_indicator_encode(double value)
{
    return (uint8_t)(value);
}

double indicators_indicator_status_parking_indicator_decode(uint8_t value)
{
    return ((double)value);
}

bool indicators_indicator_status_parking_indicator_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t indicators_indicator_status_high_beam_indicator_encode(double value)
{
    return (uint8_t)(value);
}

double indicators_indicator_status_high_beam_indicator_decode(uint8_t value)
{
    return ((double)value);
}

bool indicators_indicator_status_high_beam_indicator_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t indicators_indicator_status_low_beam_indicator_encode(double value)
{
    return (uint8_t)(value);
}

double indicators_indicator_status_low_beam_indicator_decode(uint8_t value)
{
    return ((double)value);
}

bool indicators_indicator_status_low_beam_indicator_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t indicators_indicator_status_engine_oil_temperature_indicator_encode(double value)
{
    return (uint8_t)(value);
}

double indicators_indicator_status_engine_oil_temperature_indicator_decode(uint8_t value)
{
    return ((double)value);
}

bool indicators_indicator_status_engine_oil_temperature_indicator_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t indicators_indicator_status_seat_belt_indicator_encode(double value)
{
    return (uint8_t)(value);
}

double indicators_indicator_status_seat_belt_indicator_decode(uint8_t value)
{
    return ((double)value);
}

bool indicators_indicator_status_seat_belt_indicator_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t indicators_indicator_status_engine_malfunction_indicator_encode(double value)
{
    return (uint8_t)(value);
}

double indicators_indicator_status_engine_malfunction_indicator_decode(uint8_t value)
{
    return ((double)value);
}

bool indicators_indicator_status_engine_malfunction_indicator_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t indicators_indicator_status_doors_open_indicator_encode(double value)
{
    return (uint8_t)(value);
}

double indicators_indicator_status_doors_open_indicator_decode(uint8_t value)
{
    return ((double)value);
}

bool indicators_indicator_status_doors_open_indicator_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t indicators_indicator_status_abs_warning_indicator_encode(double value)
{
    return (uint8_t)(value);
}

double indicators_indicator_status_abs_warning_indicator_decode(uint8_t value)
{
    return ((double)value);
}

bool indicators_indicator_status_abs_warning_indicator_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t indicators_indicator_status_faulty_right_indicator_encode(double value)
{
    return (uint8_t)(value);
}

double indicators_indicator_status_faulty_right_indicator_decode(uint8_t value)
{
    return ((double)value);
}

bool indicators_indicator_status_faulty_right_indicator_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t indicators_indicator_status_faulty_left_indicator_encode(double value)
{
    return (uint8_t)(value);
}

double indicators_indicator_status_faulty_left_indicator_decode(uint8_t value)
{
    return ((double)value);
}

bool indicators_indicator_status_faulty_left_indicator_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t indicators_indicator_status_engine_oil_indicator_encode(double value)
{
    return (uint8_t)(value);
}

double indicators_indicator_status_engine_oil_indicator_decode(uint8_t value)
{
    return ((double)value);
}

bool indicators_indicator_status_engine_oil_indicator_is_in_range(uint8_t value)
{
    return (value <= 1u);
}
